name: post-joke

on:
  workflow_dispatch:
    inputs: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: install-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: run
        env:
          TOKEN: ${{ $secrets.TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          go run main.go

